global:
  scrape_interval: 10s
scrape_configs:
  - job_name: "temporalmetrics"
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - "temporal.railway.internal:8000"
          - "temporal.railway.internal:8001"
          - "temporal.railway.internal:8002"
          - "temporal.railway.internal:8003"
          - "temporal.railway.internal:8004"
        labels:
          group: "server-metrics"
